name: proteomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal =9.27
  - r-base =4.5
  - r-tidyverse =2.0
  - r-rmarkdown =2.32
  - pandoc =3.11
  - r-pheatmap =1.0.13
  - bioconductor-limma =3.66
  - r-ggrepel =0.9.8
